# Set main parameters
sudo: false
language: python
python: 2.7

# Disable cache
cache: false

# command to install dependencies of dependencies
# before_install:
#   - sudo apt-get install libasound-dev

# command to install dependencies
install:
  - pip install setuptools
  - pip install pyserial
#  - pip install pyaudio

# command to run tests
script:
  - nosetests -sv ./tests/test_nose.py

# Disable notifications
notifications:
  email: false

# Only build the following branches
branches:
  only:
    - master
