# Set main parameters
sudo: true
language: python
python: 2.7

# Disable cache
cache: false

# command to install dependencies
install:
  - apt-get install libasound-dev
  - pip install setuptools pyserial pyaudio

# command to run tests
script:
  - nosetests

# Disable notifications
notifications:
  email: false

# Only build the following branches
branches:
  only:
    - master
